// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.Strategies.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Strategies.Migrations
{
    [DbContext(typeof(StrategyDbContext))]
    [Migration("20260315232109_AddBacktesting")]
    partial class AddBacktesting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.Backtest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgLoss")
                        .HasColumnType("float");

                    b.Property<double>("AvgWin")
                        .HasColumnType("float");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("FinalCapital")
                        .HasColumnType("float");

                    b.Property<double>("InitialCapital")
                        .HasColumnType("float");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<double>("LargestLoss")
                        .HasColumnType("float");

                    b.Property<double>("LargestWin")
                        .HasColumnType("float");

                    b.Property<int>("LossCount")
                        .HasColumnType("int");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("float");

                    b.Property<double>("MaxDrawdownPct")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProfitFactor")
                        .HasColumnType("float");

                    b.Property<double>("SharpeRatio")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPnl")
                        .HasColumnType("float");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.Property<double>("WinRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Backtests", "Strategies");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.BacktestTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BacktestId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExitPrice")
                        .HasColumnType("float");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pnl")
                        .HasColumnType("float");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<double>("StopLoss")
                        .HasColumnType("float");

                    b.Property<double>("TakeProfit")
                        .HasColumnType("float");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId");

                    b.ToTable("BacktestTrades", "Strategies");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRangeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PositionSizeValue")
                        .HasColumnType("float");

                    b.Property<int>("PositionSizing")
                        .HasColumnType("int");

                    b.Property<double>("RiskPerTrade")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StopLossType")
                        .HasColumnType("int");

                    b.Property<double>("StopLossValue")
                        .HasColumnType("float");

                    b.Property<int>("TakeProfitType")
                        .HasColumnType("int");

                    b.Property<double>("TakeProfitValue")
                        .HasColumnType("float");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Strategies", "Strategies");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.StrategyTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRangeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PositionSizeValue")
                        .HasColumnType("float");

                    b.Property<int>("PositionSizing")
                        .HasColumnType("int");

                    b.Property<double>("RiskPerTrade")
                        .HasColumnType("float");

                    b.Property<int>("StopLossType")
                        .HasColumnType("int");

                    b.Property<double>("StopLossValue")
                        .HasColumnType("float");

                    b.Property<int>("TakeProfitType")
                        .HasColumnType("int");

                    b.Property<double>("TakeProfitValue")
                        .HasColumnType("float");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StrategyTemplates", "Strategies");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.Backtest", b =>
                {
                    b.HasOne("TradingJournal.Modules.Strategies.Domain.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.BacktestTrade", b =>
                {
                    b.HasOne("TradingJournal.Modules.Strategies.Domain.Backtest", "Backtest")
                        .WithMany("BacktestTrades")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backtest");
                });

            modelBuilder.Entity("TradingJournal.Modules.Strategies.Domain.Backtest", b =>
                {
                    b.Navigation("BacktestTrades");
                });
#pragma warning restore 612, 618
        }
    }
}
