// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingJournal.Modules.Trades.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Trades.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260224005531_init trade database")]
    partial class inittradedatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.EmotionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PsychologyType")
                        .HasColumnType("integer");

                    b.Property<int?>("TradeHistoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("EmotionTags", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.PretradeChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListType")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TradeHistoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("PretradeChecklists", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.RiskGuardrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AccountEquity")
                        .HasColumnType("double precision");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxDailyLoss")
                        .HasColumnType("double precision");

                    b.Property<double?>("PositionSize")
                        .HasColumnType("double precision");

                    b.Property<double?>("RiskPercentage")
                        .HasColumnType("double precision");

                    b.Property<double?>("TakeProfit")
                        .HasColumnType("double precision");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RiskGuardrails", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("Pnl")
                        .HasColumnType("double precision");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("PsychologyNotes")
                        .HasColumnType("text");

                    b.Property<int?>("RiskGuardrailId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("StopLoss")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetTier1")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetTier2")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetTier3")
                        .HasColumnType("double precision");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RiskGuardrailId");

                    b.HasIndex("TradingSessionId");

                    b.ToTable("TradeHistorys", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("TradeHistoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("Screenshots", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TradingSessions", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.EmotionTag", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", null)
                        .WithMany("EmotionTags")
                        .HasForeignKey("TradeHistoryId");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.PretradeChecklist", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", null)
                        .WithMany("PretradeChecklists")
                        .HasForeignKey("TradeHistoryId");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.RiskGuardrail", "RiskGuardrail")
                        .WithMany()
                        .HasForeignKey("RiskGuardrailId");

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradingSession", "TradingSession")
                        .WithMany()
                        .HasForeignKey("TradingSessionId");

                    b.Navigation("RiskGuardrail");

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", null)
                        .WithMany("Screenshots")
                        .HasForeignKey("TradeHistoryId");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Navigation("EmotionTags");

                    b.Navigation("PretradeChecklists");

                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
