<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TradingJournal.Jobs.BackTestEngine-80e893f4-c81d-4c47-a262-ce62fa50a552</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\TradingJournal.ServiceDefaults\TradingJournal.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
